<?php
/**
 * VelocityPHP Development Server
 *
 * Starts the PHP built-in server in development mode with:
 *   - APP_ENV=development
 *   - APP_DEBUG=true
 *   - Full PHP error display
 *   - Live reload via Server-Sent Events (SSE)
 *   - Verbose banner with debug info
 *
 * Usage:
 *   php dev.php              # Start on default port 8000
 *   php dev.php 3000         # Start on custom port
 *
 * @package VelocityPHP
 * @version 1.1.0
 */

// ── Enforce development environment ──────────────────────────────────────────
putenv('APP_ENV=development');
putenv('APP_DEBUG=true');
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

// ── Configuration ─────────────────────────────────────────────────────────────
$host         = 'localhost';
$port         = isset($argv[1]) && ctype_digit($argv[1]) ? (int) $argv[1] : 8000;
$documentRoot = __DIR__ . '/public';
$serverUrl    = "http://{$host}:{$port}";

// ── Terminal colours (Windows + Unix compatible) ──────────────────────────────
$c = [
    'red'     => "\033[31m",
    'green'   => "\033[32m",
    'yellow'  => "\033[33m",
    'blue'    => "\033[34m",
    'magenta' => "\033[35m",
    'cyan'    => "\033[36m",
    'white'   => "\033[37m",
    'bold'    => "\033[1m",
    'reset'   => "\033[0m",
];

// ── Clear screen ──────────────────────────────────────────────────────────────
echo "\033[2J\033[H";

// ── Banner ────────────────────────────────────────────────────────────────────
echo "\n";
echo $c['cyan'] . $c['bold'];
echo "╔════════════════════════════════════════════════════════════════╗\n";
echo "║                                                                ║\n";
echo "║              ⚡  VELOCITYPHP  —  DEV SERVER  ⚡                ║\n";
echo "║                                                                ║\n";
echo "╚════════════════════════════════════════════════════════════════╝\n";
echo $c['reset'] . "\n";

// ── PHP version check ─────────────────────────────────────────────────────────
$phpVer = phpversion();
echo $c['blue'] . "PHP:          " . $c['reset'] . $phpVer;
if (version_compare($phpVer, '7.4.0', '>=')) {
    echo " " . $c['green'] . "✓\n" . $c['reset'];
} else {
    echo " " . $c['red'] . "✗  PHP 7.4+ required\n" . $c['reset'];
    exit(1);
}

// ── Required extension check ──────────────────────────────────────────────────
$required = ['pdo', 'json', 'mbstring', 'sqlite3'];
$missing  = array_filter($required, fn($e) => !extension_loaded($e));
if ($missing) {
    echo $c['red'] . "Missing extensions: " . implode(', ', $missing) . "\n" . $c['reset'];
    exit(1);
}

// ── Recommended extension status ─────────────────────────────────────────────
$recommended = ['opcache', 'apcu', 'zip', 'curl'];
echo "\n" . $c['blue'] . "Extensions:\n" . $c['reset'];
foreach ($required as $ext) {
    echo "  " . $c['green'] . "✓ " . $c['reset'] . str_pad($ext, 12) . " (required)\n";
}
foreach ($recommended as $ext) {
    $ok = extension_loaded($ext);
    echo "  " . ($ok ? $c['green'] . "✓ " : $c['yellow'] . "– ") . $c['reset'];
    echo str_pad($ext, 12) . ($ok ? "available\n" : "not loaded (optional)\n");
}

// ── Port availability check ───────────────────────────────────────────────────
echo "\n";
$sock = @fsockopen($host, $port, $errno, $errstr, 1);
if (is_resource($sock)) {
    fclose($sock);
    echo $c['red'] . "Port {$port} is already in use. Try: php dev.php <other-port>\n" . $c['reset'];
    exit(1);
}
echo $c['green'] . "✓ Port {$port} available\n" . $c['reset'];

// ── .env.velocity check ────────────────────────────────────────────────────────
$envFile = __DIR__ . '/.env.velocity';
if (!file_exists($envFile)) {
    echo $c['yellow'] . "⚠  No .env.velocity file found. Copy .env.velocity.example → .env.velocity before starting.\n" . $c['reset'];
}

// ── Write the dev router script ───────────────────────────────────────────────
// This router is used by `php -S` and handles:
//   GET /__livereload  → SSE endpoint that pushes "reload" when files change
//   everything else    → normal app, with live-reload <script> injected into HTML
$routerPath = sys_get_temp_dir() . '/velocity_dev_router_' . $port . '.php';
$watchDirs  = [__DIR__ . '/src', __DIR__ . '/public'];
$watchDirsJson = json_encode($watchDirs);
$docRootEsc = addslashes($documentRoot);

$routerCode = <<<'PHP'
<?php
// ── VelocityPHP live-reload dev router ───────────────────────────────────────
// Generated by dev.php – do not edit manually.

putenv('APP_ENV=development');
putenv('APP_DEBUG=true');
ini_set('display_errors', '1');
error_reporting(E_ALL);

$watchDirs   = WATCH_DIRS_PLACEHOLDER;
$documentRoot = 'DOCROOT_PLACEHOLDER';

// ── SSE live-reload endpoint ──────────────────────────────────────────────────
if ($_SERVER['REQUEST_URI'] === '/__livereload') {
    // Build snapshot of all watched file mtimes
    function getFileHash(array $dirs): string {
        $state = [];
        foreach ($dirs as $dir) {
            if (!is_dir($dir)) continue;
            $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,
                FilesystemIterator::SKIP_DOTS | FilesystemIterator::UNIX_PATHS));
            foreach ($it as $file) {
                if ($file->isFile()) {
                    $state[$file->getPathname()] = $file->getMTime();
                }
            }
        }
        ksort($state);
        return md5(serialize($state));
    }

    set_time_limit(0);
    ignore_user_abort(false);

    header('Content-Type: text/event-stream');
    header('Cache-Control: no-cache');
    header('X-Accel-Buffering: no');

    $lastHash = getFileHash($watchDirs);

    // Send an initial "connected" ping
    echo "data: connected\n\n";
    if (ob_get_level()) ob_flush();
    flush();

    while (true) {
        if (connection_aborted()) break;

        sleep(1);

        $hash = getFileHash($watchDirs);
        if ($hash !== $lastHash) {
            $lastHash = $hash;
            echo "data: reload\n\n";
            if (ob_get_level()) ob_flush();
            flush();
        }

        // Keepalive comment every ~15 s to avoid proxy timeouts
        static $ticks = 0;
        if (++$ticks % 15 === 0) {
            echo ": keepalive\n\n";
            if (ob_get_level()) ob_flush();
            flush();
        }
    }
    exit;
}

// ── Normal request: proxy through public/index.php and inject live-reload ────
$uri = urldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));

// Serve real static files directly
if ($uri !== '/' && file_exists($documentRoot . $uri) && !is_dir($documentRoot . $uri)) {
    return false; // Let PHP built-in server serve the file
}

// Capture the application output
ob_start();
chdir($documentRoot);
$_SERVER['DOCUMENT_ROOT'] = $documentRoot;
require $documentRoot . '/index.php';
$html = ob_get_clean();

// Inject live-reload client just before </body>
$lrScript = '<script>(function(){' .
    'var s=new EventSource("/__livereload");' .
    's.onmessage=function(e){if(e.data==="reload"){location.reload();}};' .
    's.onerror=function(){setTimeout(function(){location.reload();},2000);};' .
'})();</script>';

$html = str_replace('</body>', $lrScript . "\n</body>", $html);

echo $html;
PHP;

// Replace placeholders
$routerCode = str_replace('WATCH_DIRS_PLACEHOLDER', $watchDirsJson, $routerCode);
$routerCode = str_replace('DOCROOT_PLACEHOLDER', $docRootEsc, $routerCode);

file_put_contents($routerPath, $routerCode);

// ── Server info box ───────────────────────────────────────────────────────────
echo "\n";
echo $c['blue'] . "┌────────────────────────────────────────────────────────────────┐\n" . $c['reset'];
$rows = [
    "Mode"        => $c['magenta'] . "DEVELOPMENT  (errors visible, debug ON)" . $c['reset'],
    "URL"         => $c['green']   . $c['bold'] . $serverUrl . $c['reset'],
    "Root"        => $c['yellow']  . $documentRoot . $c['reset'],
    "PHP"         => $c['cyan']    . $phpVer . $c['reset'],
    "Live Reload" => $c['green']   . "enabled  (SSE /__livereload)" . $c['reset'],
    "OPcache"     => extension_loaded('opcache') ? $c['green'] . "enabled" . $c['reset'] : $c['yellow'] . "disabled" . $c['reset'],
];
foreach ($rows as $label => $value) {
    echo $c['blue'] . "│ " . $c['reset'];
    echo str_pad($label . ":", 14) . $value . "\n";
}
echo $c['blue'] . "└────────────────────────────────────────────────────────────────┘\n" . $c['reset'];

// ── Quick links ───────────────────────────────────────────────────────────────
echo "\n" . $c['cyan'] . $c['bold'] . "Quick Links:\n" . $c['reset'];

// Discover page routes automatically from src/views/pages/
$pagesDir = $documentRoot . '/../src/views/pages';
$routes   = ['/'];
if (is_dir($pagesDir)) {
    foreach (new DirectoryIterator($pagesDir) as $entry) {
        if ($entry->isDir() && !$entry->isDot()) {
            $routes[] = '/' . $entry->getFilename();
        }
    }
}
sort($routes);
foreach ($routes as $route) {
    echo "  " . $c['blue'] . $serverUrl . $route . $c['reset'] . "\n";
}

// ── Tips ──────────────────────────────────────────────────────────────────────
echo "\n" . $c['yellow'] . "Dev Tips:\n" . $c['reset'];
echo $c['yellow'] . "  • Browser auto-reloads when PHP/view files change\n" . $c['reset'];
echo $c['yellow'] . "  • Errors are displayed in the browser (APP_DEBUG=true)\n" . $c['reset'];
echo $c['yellow'] . "  • Restart this script after adding new routes or config changes\n" . $c['reset'];
echo $c['yellow'] . "  • Use php start.php for production-style testing\n" . $c['reset'];
echo "\n" . $c['cyan'] . "Press Ctrl+C to stop\n\n" . $c['reset'];
echo $c['green'] . $c['bold'] . str_repeat("═", 66) . "\n\n" . $c['reset'];

// ── Launch server ─────────────────────────────────────────────────────────────
chdir($documentRoot);
$cmd = sprintf(
    'php -S %s:%d -t %s %s',
    escapeshellarg($host),
    $port,
    escapeshellarg($documentRoot),
    escapeshellarg($routerPath)
);
passthru($cmd);

// ── Cleanup router temp file on exit ──────────────────────────────────────────
@unlink($routerPath);
